### ISSUE TITLE
이미 커밋한 내용의 메시지만 변경하는 방법 (모든건 그대로 유지)

### ISSUE THREAD

**Issue by ks2colorworld** [colorworld-kr/test-git#2]
<img width="854" alt="image" src="https://github.com/colorworld-kr/test-git/assets/476848/5befd9c8-cd37-4176-a1fa-c0bb101114da">

- (x실패) https://xtring-dev.tistory.com/entry/Git-이미-commit한-메세지-수정하기-바로-이전그-전리모트-commit

**Comment by ks2colorworld** [comment]
<img width="826" alt="image" src="https://github.com/colorworld-kr/test-git/assets/476848/4b3345e3-9797-4549-a04b-4e29061f72b1">

**Comment by ks2colorworld** [comment]
<img width="859" alt="image" src="https://github.com/colorworld-kr/test-git/assets/476848/e86010e2-fdbd-4311-a6f5-4bf4da9108c7">

**Comment by ks2colorworld** [comment]
- ### 기대와 다른 모습

<img width="863" alt="image" src="https://github.com/colorworld-kr/test-git/assets/476848/d9b1d255-9798-4649-84fc-08ed092a76b3">

**Comment by youngme92** [comment]
이 작업은 주의해야 합니다. 왜냐하면 이렇게 하면 깃의 히스토리를 변경하는 것이기 때문입니다.

다른 사람들과 공유하고 있는 저장소라면 이런 히스토리 변경은 문제를 일으킬 수 있습니다. 그러니 반드시 필요한 경우에만 사용해주세요.

가장 먼저, 변경하고 싶은 커밋까지의 히스토리를 보려면 다음 명령어를 사용합니다: git log
이후, 변경하고 싶은 커밋의 해시를 복사합니다.
그 다음, git rebase -i [복사한 커밋의 해시]^ 명령어를 실행합니다. (여기서 ^ 기호는 복사한 커밋의 부모 커밋을 가리킵니다.)
이 명령어를 실행하면 텍스트 에디터가 열리는데, 이곳에서 'pick'이라 적힌 부분을 'reword'로 변경하고 저장 후 종료합니다.
그럼 다시 텍스트 에디터가 열리면서 커밋 메세지를 수정할 수 있는 화면이 나타납니다. 메세지를 수정한 후 저장하고 종료하면 됩니다.
마지막으로, git push origin [브랜치 이름] --force 명령어로 변경된 히스토리를 강제로 푸시합니다.
주의: --force 옵션은 기존의 히스토리를 덮어쓰는 동작이므로, 다른 사람들과 공유하는 저장소에는 사용하지 않는 것이 좋습니다.

이렇게 하면 커밋 메세지를 변경할 수 있습니다. 다만, 이 과정은 고급 사용자를 위한 것이므로 신중히 사용해야 합니다.

<img width="786" alt="스크린샷 2023-12-26 오후 7 01 45" src="https://github.com/colorworld-kr/test-git/assets/50010735/a254d54d-46f7-4fdb-b31c-1a104e32aa63">

정리하면 main 브랜치에서 이전의 커밋기록을 리베이스함으로써 커밋을 재작성하게 됩니다. 
그렇기때문에 이전 그림처럼 edit 브랜치에서 merge 했다는 기록이 사라지지만 이전 커밋의 메세지를 변경하는 목적은 달성할 수 있습니다.  (main 브랜치의 이전 커밋 메세지를 변경하였지만 만약 타 브랜치에도 메세지를 변경하고 싶다면 타 브랜치에서도 rebase 작업을 통해 변경해야합니다.😅)

**Comment by ks2colorworld** [comment]
음... 메시지 하나 바꾸는게 이렇게 복잡한 거면 안하는게 맞을듯 싶습니다.

**Comment by ks2colorworld** [comment]
# 다시 시도 (원격저장소에는 올리지 않은 상태)
<img width="726" alt="image" src="https://github.com/colorworld-kr/test-git/assets/476848/166b8d89-d819-4b90-984e-53951a22730b">
<img width="833" alt="image" src="https://github.com/colorworld-kr/test-git/assets/476848/5c70d742-76cb-4dd8-9c48-77e06d60803a">
<img width="814" alt="image" src="https://github.com/colorworld-kr/test-git/assets/476848/54e94845-4f14-46e9-9731-16f18cf04e42">

## 올바른 결과물 
<img width="760" alt="image" src="https://github.com/colorworld-kr/test-git/assets/476848/ae018023-0387-4529-b0c2-e93b66752648">

**Comment by ks2colorworld** [comment]
# 다시 시도 (main 브랜치에 머지한 상태 + 원격저장소에는 올리지 않은 상태)
<img width="750" alt="image" src="https://github.com/colorworld-kr/test-git/assets/476848/b1ab7089-53a0-4e0c-aa0e-d0286c263293">

- ## 1. main 브랜치를 머지하기 전 커밋으로 옮긴다. 
<img width="896" alt="image" src="https://github.com/colorworld-kr/test-git/assets/476848/b2bd6831-141e-4c48-982a-4678b917f009">
<img width="691" alt="image" src="https://github.com/colorworld-kr/test-git/assets/476848/122e8ec9-2807-4cfa-89cc-0a727a935d4e">

- ## 2. 브랜치를 옮긴 후 바로 위에 설명한 [(comment)](https://github.com/colorworld-kr/test-git/issues/2#issuecomment-1869452048)와 같이 rebase 작업을 동일하게 진행한다.
<img width="745" alt="image" src="https://github.com/colorworld-kr/test-git/assets/476848/6b7cb2df-c33f-4f9a-9ecc-16fcb7e69988">

- ## 3. main 브랜치에 머지한다. (올바른 결과물)
<img width="720" alt="image" src="https://github.com/colorworld-kr/test-git/assets/476848/6719e300-d3e0-4e6e-bbcb-5b27a8e8c6b1">

**Comment by ks2colorworld** [comment]
# 다시 시도 (main 브랜치에 머지한 상태 + 원격저장소에 올라간 상태)
<img width="712" alt="image" src="https://github.com/colorworld-kr/test-git/assets/476848/1ab7ffda-8c18-4dcf-874e-3c0a66380f4d">

- ## 1. 위 [comment 설명](https://github.com/colorworld-kr/test-git/issues/2#issuecomment-1869470766)과 같이 rebase를 진행한다.
<img width="777" alt="image" src="https://github.com/colorworld-kr/test-git/assets/476848/324c430a-27ee-478b-b4fc-11248070018a">
<img width="744" alt="image" src="https://github.com/colorworld-kr/test-git/assets/476848/48d32531-3e76-42e0-88b1-acadad1da82e">
<img width="775" alt="image" src="https://github.com/colorworld-kr/test-git/assets/476848/6c743577-3fbe-4414-b5b3-b73d453b648b">

- ## 2. main 브랜치를 강제 push한다. 
<img width="896" alt="image" src="https://github.com/colorworld-kr/test-git/assets/476848/8e2b8e2b-7e08-484e-bcb3-2ea4bdb60280">

- ## 올바른 결과물 
<img width="730" alt="image" src="https://github.com/colorworld-kr/test-git/assets/476848/6c5f4703-1f34-4879-9a63-a48e06428d60">

**Comment by ks2colorworld** [comment]
# 훨씬 더 깊고 복잡한 곳의 커밋 메시지를 수정해야 하는 상황은? 
<img width="724" alt="image" src="https://github.com/colorworld-kr/test-git/assets/476848/129ee9c1-fcfe-43d0-8fb5-bcc2c2d3c692">
 
- ## 개념 (해보진 않음)
<img width="1009" alt="image" src="https://github.com/colorworld-kr/test-git/assets/476848/e5fb8bff-9274-47c5-b6e3-7524a66a7b85">

1. `main` 브랜치를 `1.` 커밋으로 `hard  reset`한다.
2. `2.` 브랜치로 체크아웃한다. 
3. `3.` 커밋 메시지를 수정한다. (위 comment들 참고)
4. `main` 브랜치로 체크아웃한다.
5. `2.`, `4.` 브랜치들을 순서대로 머지한다.
6. `main` 브랜치를 `force push` 한다. (필요에 따라 다른 브랜치들도 `force push` 한다.)

**Comment by ks2colorworld** [comment]
- #3 (다음과제)
